# 1. 온라인 상품 판매 데이터
SELECT 
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL # 합치기

# 2. 오프라인 상품 판매 데이터
SELECT 
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

# 3. 정렬
ORDER BY 
    SALES_DATE ASC, 
    PRODUCT_ID ASC, 
    USER_ID ASC;


