WITH RECURSIVE ECOLI_GEN AS(
    -- 1. Root (1세대) 찾기
    SELECT ID,PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    -- 2. 자식 세대 추적 (재귀)
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    INNER JOIN ECOLI_GEN G ON E.PARENT_ID = G.ID
)

-- 3. 자식이 없는 개체 필터링 및 세대별 집계
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_GEN G
-- 자식이 없는 개체만 필터링
WHERE NOT EXISTS(
    SELECT 1
    FROM ECOLI_DATA
    WHERE PARENT_ID = G.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;