SELECT
    T.HISTORY_ID,
    ROUND(T.DAILY_FEE * T.DURATION * (100- COALESCE(P.DISCOUNT_RATE,0))/100,0) AS FEE
FROM (
    SELECT
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE,H.START_DATE) + 1 AS DURATION,
        CASE
            WHEN DATEDIFF(H.END_DATE,H.START_DATE) + 1 >=90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE,H.START_DATE) + 1 >=30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE,H.START_DATE) + 1 >=7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
    ) AS T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON T.DURATION_TYPE = P.DURATION_TYPE
    AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;