-- 코드를 입력하세요
SELECT
    F.FLAVOR
FROM FIRST_HALF F
JOIN(
    -- JULY 테이블에서 맛별로 총 주문량을 먼저 합산
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_TOTAL) DESC
LIMIT 3;
