WITH RECURSIVE TIME_LIST AS (
    -- 초기값 0 
    SELECT 0 AS HOUR
    
    UNION ALL
    -- 23시까지 증가
    SELECT HOUR + 1 FROM TIME_LIST WHERE HOUR < 23
)

SELECT 
    T.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_LIST T
LEFT JOIN ANIMAL_OUTS A ON HOUR(A.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;