SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    -- 분화된 연도별 최대 크기를 미리 계산
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)

) M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR ASC, YEAR_DEV ASC;