WITH DEV_SKILLS AS (
    SELECT
        D.ID, D.EMAIL,D.FIRST_NAME,D.LAST_NAME,
        -- 각 사원이 가진 스킬을 비트 연산으로 체크
        MAX(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) as HAS_FE,
        MAX(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) as HAS_PYTHON,
        MAX(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) as HAS_CSHARP
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) > 0
    GROUP BY D.ID,D.EMAIL,D.FIRST_NAME,D.LAST_NAME
)
SELECT
    CASE
        WHEN HAS_FE = 1 AND HAS_PYTHON = 1 THEN 'A'
        WHEN HAS_CSHARP = 1  THEN 'B'
        WHEN HAS_FE = 1 THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEV_SKILLS
-- GRADE가 NULL 인 경우는 제외
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;